services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb+srv://bllysm23:Carefor123@ct-lab.k2gqo.mongodb.net/ct-lab?retryWrites=true&w=majority&appName=CT-lab
      - JWT_SECRET=your_jwt_secret_here
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongodb

#   mongodb:
#     image: mongo:5
#     ports:
#       - "27017:27017"
#     volumes:
#       - mongodb_data:/data/db

# volumes:
#   mongodb_data: